// Code generated by go-swagger; DO NOT EDIT.

// ==================================================================================
// Unless otherwise specified, all software contained herein is licensed
// under the Apache License, Version 2.0 (the "Software License");
// you may not use this software except in compliance with the Software
// License. You may obtain a copy of the Software License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the Software License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the Software License for the specific language governing permissions
// and limitations under the Software License.
//
// ==================================================================================
//
// Unless otherwise specified, all documentation contained herein is licensed
// under the Creative Commons License, Attribution 4.0 Intl. (the
// "Documentation License"); you may not use this documentation except in
// compliance with the Documentation License. You may obtain a copy of the
// Documentation License at
//
// https://creativecommons.org/licenses/by/4.0/
//
// Unless required by applicable law or agreed to in writing, documentation
// distributed under the Documentation License is distributed on an "AS IS"
// BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the Documentation License for the specific language governing
// permissions and limitations under the Documentation License.
// ==================================================================================
//
//

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ProvideXappHandleCreatedCode is the HTTP code returned for type ProvideXappHandleCreated
const ProvideXappHandleCreatedCode int = 201

/*ProvideXappHandleCreated Callback received

swagger:response provideXappHandleCreated
*/
type ProvideXappHandleCreated struct {
}

// NewProvideXappHandleCreated creates ProvideXappHandleCreated with default headers values
func NewProvideXappHandleCreated() *ProvideXappHandleCreated {

	return &ProvideXappHandleCreated{}
}

// WriteResponse to the client
func (o *ProvideXappHandleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// ProvideXappHandleBadRequestCode is the HTTP code returned for type ProvideXappHandleBadRequest
const ProvideXappHandleBadRequestCode int = 400

/*ProvideXappHandleBadRequest Invalid data

swagger:response provideXappHandleBadRequest
*/
type ProvideXappHandleBadRequest struct {
}

// NewProvideXappHandleBadRequest creates ProvideXappHandleBadRequest with default headers values
func NewProvideXappHandleBadRequest() *ProvideXappHandleBadRequest {

	return &ProvideXappHandleBadRequest{}
}

// WriteResponse to the client
func (o *ProvideXappHandleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
