// Code generated by go-swagger; DO NOT EDIT.

// ==================================================================================
// Unless otherwise specified, all software contained herein is licensed
// under the Apache License, Version 2.0 (the "Software License");
// you may not use this software except in compliance with the Software
// License. You may obtain a copy of the Software License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the Software License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the Software License for the specific language governing permissions
// and limitations under the Software License.
//
// ==================================================================================
//
// Unless otherwise specified, all documentation contained herein is licensed
// under the Creative Commons License, Attribution 4.0 Intl. (the
// "Documentation License"); you may not use this documentation except in
// compliance with the Documentation License. You may obtain a copy of the
// Documentation License at
//
// https://creativecommons.org/licenses/by/4.0/
//
// Unless required by applicable law or agreed to in writing, documentation
// distributed under the Documentation License is distributed on an "AS IS"
// BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the Documentation License for the specific language governing
// permissions and limitations under the Documentation License.
// ==================================================================================
//
//

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteRouteByIDNoContentCode is the HTTP code returned for type DeleteRouteByIDNoContent
const DeleteRouteByIDNoContentCode int = 204

/*DeleteRouteByIDNoContent Route deleted

swagger:response deleteRouteByIdNoContent
*/
type DeleteRouteByIDNoContent struct {
}

// NewDeleteRouteByIDNoContent creates DeleteRouteByIDNoContent with default headers values
func NewDeleteRouteByIDNoContent() *DeleteRouteByIDNoContent {

	return &DeleteRouteByIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteRouteByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteRouteByIDBadRequestCode is the HTTP code returned for type DeleteRouteByIDBadRequest
const DeleteRouteByIDBadRequestCode int = 400

/*DeleteRouteByIDBadRequest Invalid route ID supplied

swagger:response deleteRouteByIdBadRequest
*/
type DeleteRouteByIDBadRequest struct {
}

// NewDeleteRouteByIDBadRequest creates DeleteRouteByIDBadRequest with default headers values
func NewDeleteRouteByIDBadRequest() *DeleteRouteByIDBadRequest {

	return &DeleteRouteByIDBadRequest{}
}

// WriteResponse to the client
func (o *DeleteRouteByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteRouteByIDNotFoundCode is the HTTP code returned for type DeleteRouteByIDNotFound
const DeleteRouteByIDNotFoundCode int = 404

/*DeleteRouteByIDNotFound Route not found

swagger:response deleteRouteByIdNotFound
*/
type DeleteRouteByIDNotFound struct {
}

// NewDeleteRouteByIDNotFound creates DeleteRouteByIDNotFound with default headers values
func NewDeleteRouteByIDNotFound() *DeleteRouteByIDNotFound {

	return &DeleteRouteByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteRouteByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
