// Code generated by go-swagger; DO NOT EDIT.

// ==================================================================================
// Unless otherwise specified, all software contained herein is licensed
// under the Apache License, Version 2.0 (the "Software License");
// you may not use this software except in compliance with the Software
// License. You may obtain a copy of the Software License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the Software License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the Software License for the specific language governing permissions
// and limitations under the Software License.
//
// ==================================================================================
//
// Unless otherwise specified, all documentation contained herein is licensed
// under the Creative Commons License, Attribution 4.0 Intl. (the
// "Documentation License"); you may not use this documentation except in
// compliance with the Documentation License. You may obtain a copy of the
// Documentation License at
//
// https://creativecommons.org/licenses/by/4.0/
//
// Unless required by applicable law or agreed to in writing, documentation
// distributed under the Documentation License is distributed on an "AS IS"
// BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the Documentation License for the specific language governing
// permissions and limitations under the Documentation License.
// ==================================================================================
//
//

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateRouteNoContentCode is the HTTP code returned for type UpdateRouteNoContent
const UpdateRouteNoContentCode int = 204

/*UpdateRouteNoContent Route updated

swagger:response updateRouteNoContent
*/
type UpdateRouteNoContent struct {
}

// NewUpdateRouteNoContent creates UpdateRouteNoContent with default headers values
func NewUpdateRouteNoContent() *UpdateRouteNoContent {

	return &UpdateRouteNoContent{}
}

// WriteResponse to the client
func (o *UpdateRouteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// UpdateRouteBadRequestCode is the HTTP code returned for type UpdateRouteBadRequest
const UpdateRouteBadRequestCode int = 400

/*UpdateRouteBadRequest Invalid route ID supplied

swagger:response updateRouteBadRequest
*/
type UpdateRouteBadRequest struct {
}

// NewUpdateRouteBadRequest creates UpdateRouteBadRequest with default headers values
func NewUpdateRouteBadRequest() *UpdateRouteBadRequest {

	return &UpdateRouteBadRequest{}
}

// WriteResponse to the client
func (o *UpdateRouteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateRouteNotFoundCode is the HTTP code returned for type UpdateRouteNotFound
const UpdateRouteNotFoundCode int = 404

/*UpdateRouteNotFound Route not found

swagger:response updateRouteNotFound
*/
type UpdateRouteNotFound struct {
}

// NewUpdateRouteNotFound creates UpdateRouteNotFound with default headers values
func NewUpdateRouteNotFound() *UpdateRouteNotFound {

	return &UpdateRouteNotFound{}
}

// WriteResponse to the client
func (o *UpdateRouteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
