// Code generated by go-swagger; DO NOT EDIT.

// ==================================================================================
// Unless otherwise specified, all software contained herein is licensed
// under the Apache License, Version 2.0 (the "Software License");
// you may not use this software except in compliance with the Software
// License. You may obtain a copy of the Software License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the Software License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the Software License for the specific language governing permissions
// and limitations under the Software License.
//
// ==================================================================================
//
// Unless otherwise specified, all documentation contained herein is licensed
// under the Creative Commons License, Attribution 4.0 Intl. (the
// "Documentation License"); you may not use this documentation except in
// compliance with the Documentation License. You may obtain a copy of the
// Documentation License at
//
// https://creativecommons.org/licenses/by/4.0/
//
// Unless required by applicable law or agreed to in writing, documentation
// distributed under the Documentation License is distributed on an "AS IS"
// BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the Documentation License for the specific language governing
// permissions and limitations under the Documentation License.
// ==================================================================================
//
//

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is the Swagger/OpenAPI 2.0 definition of Routing Manager's Northbound API.",
    "title": "Routing Manager",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.3.0"
  },
  "host": "rtmgr",
  "basePath": "/v1",
  "paths": {
    "/handles": {
      "get": {
        "description": "Placeholder for further usage.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "handle"
        ],
        "summary": "Placeholder for further usage",
        "operationId": "get_handles",
        "responses": {
          "200": {
            "description": "Dummy response"
          }
        }
      }
    },
    "/handles/xapp-handle": {
      "post": {
        "description": "By performing a POST method on the xapp-handle resource, the API caller is able to perform a callback on Routing Manager.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "handle"
        ],
        "summary": "Provide callback",
        "operationId": "provide_xapp_handle",
        "parameters": [
          {
            "description": "xApp related callback data",
            "name": "xapp-callback-data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/xapp-callback-data"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Callback received"
          },
          "400": {
            "description": "Invalid data"
          }
        }
      }
    },
    "/handles/xapp-subscription-handle": {
      "post": {
        "description": "By performing a POST method on the xapp-subscription-handle resource, the API caller is able to update the Routing manager about the creation of new subscription by an Xapp instance.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "handle"
        ],
        "summary": "API for updating about new xapp subscription",
        "operationId": "provide_xapp_subscription_handle",
        "parameters": [
          {
            "description": "xApp related subscription data",
            "name": "xapp-subscription-data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/xapp-subscription-data"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Xapp Subscription data received"
          },
          "400": {
            "description": "Invalid data"
          }
        }
      }
    },
    "/health": {
      "get": {
        "description": "By performing a GET method on the health resource, the API caller is able to retrieve the health of Routing Manager",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Retrive the health of Routing Manager",
        "operationId": "get_health",
        "responses": {
          "200": {
            "description": "The health of the system",
            "schema": {
              "$ref": "#/definitions/health-status"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "health-status": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "healthy",
            "unhealthy"
          ]
        }
      }
    },
    "xapp-callback-data": {
      "type": "object",
      "properties": {
        "data": {
          "type": "string"
        },
        "data-version": {
          "type": "integer",
          "format": "int64"
        },
        "event": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "xapp-subscription-data": {
      "type": "object",
      "required": [
        "address",
        "port",
        "subscription_id"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "port": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535
        },
        "subscription_id": {
          "type": "integer",
          "format": "int16"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Available handles",
      "name": "handle"
    },
    {
      "description": "Health of the system",
      "name": "health"
    }
  ],
  "externalDocs": {
    "description": "Routing Manager",
    "url": "http://placeholder"
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is the Swagger/OpenAPI 2.0 definition of Routing Manager's Northbound API.",
    "title": "Routing Manager",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.3.0"
  },
  "host": "rtmgr",
  "basePath": "/v1",
  "paths": {
    "/handles": {
      "get": {
        "description": "Placeholder for further usage.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "handle"
        ],
        "summary": "Placeholder for further usage",
        "operationId": "get_handles",
        "responses": {
          "200": {
            "description": "Dummy response"
          }
        }
      }
    },
    "/handles/xapp-handle": {
      "post": {
        "description": "By performing a POST method on the xapp-handle resource, the API caller is able to perform a callback on Routing Manager.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "handle"
        ],
        "summary": "Provide callback",
        "operationId": "provide_xapp_handle",
        "parameters": [
          {
            "description": "xApp related callback data",
            "name": "xapp-callback-data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/xapp-callback-data"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Callback received"
          },
          "400": {
            "description": "Invalid data"
          }
        }
      }
    },
    "/handles/xapp-subscription-handle": {
      "post": {
        "description": "By performing a POST method on the xapp-subscription-handle resource, the API caller is able to update the Routing manager about the creation of new subscription by an Xapp instance.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "handle"
        ],
        "summary": "API for updating about new xapp subscription",
        "operationId": "provide_xapp_subscription_handle",
        "parameters": [
          {
            "description": "xApp related subscription data",
            "name": "xapp-subscription-data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/xapp-subscription-data"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Xapp Subscription data received"
          },
          "400": {
            "description": "Invalid data"
          }
        }
      }
    },
    "/health": {
      "get": {
        "description": "By performing a GET method on the health resource, the API caller is able to retrieve the health of Routing Manager",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Retrive the health of Routing Manager",
        "operationId": "get_health",
        "responses": {
          "200": {
            "description": "The health of the system",
            "schema": {
              "$ref": "#/definitions/health-status"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "health-status": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "healthy",
            "unhealthy"
          ]
        }
      }
    },
    "xapp-callback-data": {
      "type": "object",
      "properties": {
        "data": {
          "type": "string"
        },
        "data-version": {
          "type": "integer",
          "format": "int64"
        },
        "event": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "xapp-subscription-data": {
      "type": "object",
      "required": [
        "address",
        "port",
        "subscription_id"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "port": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535,
          "minimum": 0
        },
        "subscription_id": {
          "type": "integer",
          "format": "int16"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Available handles",
      "name": "handle"
    },
    {
      "description": "Health of the system",
      "name": "health"
    }
  ],
  "externalDocs": {
    "description": "Routing Manager",
    "url": "http://placeholder"
  }
}`))
}
