// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSubscriptionReader is a Reader for the DeleteSubscription structure.
type DeleteSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteSubscriptionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteSubscriptionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSubscriptionNoContent creates a DeleteSubscriptionNoContent with default headers values
func NewDeleteSubscriptionNoContent() *DeleteSubscriptionNoContent {
	return &DeleteSubscriptionNoContent{}
}

/*DeleteSubscriptionNoContent handles this case with default header values.

Successful deletion of subscription
*/
type DeleteSubscriptionNoContent struct {
}

func (o *DeleteSubscriptionNoContent) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}][%d] deleteSubscriptionNoContent ", 204)
}

func (o *DeleteSubscriptionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSubscriptionBadRequest creates a DeleteSubscriptionBadRequest with default headers values
func NewDeleteSubscriptionBadRequest() *DeleteSubscriptionBadRequest {
	return &DeleteSubscriptionBadRequest{}
}

/*DeleteSubscriptionBadRequest handles this case with default header values.

Invalid subscription supplied
*/
type DeleteSubscriptionBadRequest struct {
}

func (o *DeleteSubscriptionBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}][%d] deleteSubscriptionBadRequest ", 400)
}

func (o *DeleteSubscriptionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
