// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSubscriptionByIDParams creates a new GetSubscriptionByIDParams object
// with the default values initialized.
func NewGetSubscriptionByIDParams() *GetSubscriptionByIDParams {
	var ()
	return &GetSubscriptionByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubscriptionByIDParamsWithTimeout creates a new GetSubscriptionByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSubscriptionByIDParamsWithTimeout(timeout time.Duration) *GetSubscriptionByIDParams {
	var ()
	return &GetSubscriptionByIDParams{

		timeout: timeout,
	}
}

// NewGetSubscriptionByIDParamsWithContext creates a new GetSubscriptionByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSubscriptionByIDParamsWithContext(ctx context.Context) *GetSubscriptionByIDParams {
	var ()
	return &GetSubscriptionByIDParams{

		Context: ctx,
	}
}

// NewGetSubscriptionByIDParamsWithHTTPClient creates a new GetSubscriptionByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSubscriptionByIDParamsWithHTTPClient(client *http.Client) *GetSubscriptionByIDParams {
	var ()
	return &GetSubscriptionByIDParams{
		HTTPClient: client,
	}
}

/*GetSubscriptionByIDParams contains all the parameters to send to the API endpoint
for the get subscription by Id operation typically these are written to a http.Request
*/
type GetSubscriptionByIDParams struct {

	/*SubscriptionID
	  ID of subscription

	*/
	SubscriptionID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get subscription by Id params
func (o *GetSubscriptionByIDParams) WithTimeout(timeout time.Duration) *GetSubscriptionByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get subscription by Id params
func (o *GetSubscriptionByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get subscription by Id params
func (o *GetSubscriptionByIDParams) WithContext(ctx context.Context) *GetSubscriptionByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get subscription by Id params
func (o *GetSubscriptionByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get subscription by Id params
func (o *GetSubscriptionByIDParams) WithHTTPClient(client *http.Client) *GetSubscriptionByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get subscription by Id params
func (o *GetSubscriptionByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubscriptionID adds the subscriptionID to the get subscription by Id params
func (o *GetSubscriptionByIDParams) WithSubscriptionID(subscriptionID int64) *GetSubscriptionByIDParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the get subscription by Id params
func (o *GetSubscriptionByIDParams) SetSubscriptionID(subscriptionID int64) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubscriptionByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", swag.FormatInt64(o.SubscriptionID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
