// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllXappsParams creates a new GetAllXappsParams object
// with the default values initialized.
func NewGetAllXappsParams() *GetAllXappsParams {

	return &GetAllXappsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllXappsParamsWithTimeout creates a new GetAllXappsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllXappsParamsWithTimeout(timeout time.Duration) *GetAllXappsParams {

	return &GetAllXappsParams{

		timeout: timeout,
	}
}

// NewGetAllXappsParamsWithContext creates a new GetAllXappsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllXappsParamsWithContext(ctx context.Context) *GetAllXappsParams {

	return &GetAllXappsParams{

		Context: ctx,
	}
}

// NewGetAllXappsParamsWithHTTPClient creates a new GetAllXappsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllXappsParamsWithHTTPClient(client *http.Client) *GetAllXappsParams {

	return &GetAllXappsParams{
		HTTPClient: client,
	}
}

/*GetAllXappsParams contains all the parameters to send to the API endpoint
for the get all xapps operation typically these are written to a http.Request
*/
type GetAllXappsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all xapps params
func (o *GetAllXappsParams) WithTimeout(timeout time.Duration) *GetAllXappsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all xapps params
func (o *GetAllXappsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all xapps params
func (o *GetAllXappsParams) WithContext(ctx context.Context) *GetAllXappsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all xapps params
func (o *GetAllXappsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all xapps params
func (o *GetAllXappsParams) WithHTTPClient(client *http.Client) *GetAllXappsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all xapps params
func (o *GetAllXappsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllXappsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
