// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetXappByNameParams creates a new GetXappByNameParams object
// with the default values initialized.
func NewGetXappByNameParams() *GetXappByNameParams {
	var ()
	return &GetXappByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetXappByNameParamsWithTimeout creates a new GetXappByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetXappByNameParamsWithTimeout(timeout time.Duration) *GetXappByNameParams {
	var ()
	return &GetXappByNameParams{

		timeout: timeout,
	}
}

// NewGetXappByNameParamsWithContext creates a new GetXappByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetXappByNameParamsWithContext(ctx context.Context) *GetXappByNameParams {
	var ()
	return &GetXappByNameParams{

		Context: ctx,
	}
}

// NewGetXappByNameParamsWithHTTPClient creates a new GetXappByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetXappByNameParamsWithHTTPClient(client *http.Client) *GetXappByNameParams {
	var ()
	return &GetXappByNameParams{
		HTTPClient: client,
	}
}

/*GetXappByNameParams contains all the parameters to send to the API endpoint
for the get xapp by name operation typically these are written to a http.Request
*/
type GetXappByNameParams struct {

	/*XAppName
	  Name of xApp

	*/
	XAppName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get xapp by name params
func (o *GetXappByNameParams) WithTimeout(timeout time.Duration) *GetXappByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get xapp by name params
func (o *GetXappByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get xapp by name params
func (o *GetXappByNameParams) WithContext(ctx context.Context) *GetXappByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get xapp by name params
func (o *GetXappByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get xapp by name params
func (o *GetXappByNameParams) WithHTTPClient(client *http.Client) *GetXappByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get xapp by name params
func (o *GetXappByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAppName adds the xAppName to the get xapp by name params
func (o *GetXappByNameParams) WithXAppName(xAppName string) *GetXappByNameParams {
	o.SetXAppName(xAppName)
	return o
}

// SetXAppName adds the xAppName to the get xapp by name params
func (o *GetXappByNameParams) SetXAppName(xAppName string) {
	o.XAppName = xAppName
}

// WriteToRequest writes these params to a swagger request
func (o *GetXappByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param xAppName
	if err := r.SetPathParam("xAppName", o.XAppName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
