// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	appmgr_model "routing-manager/pkg/appmgr_model"
)

// GetSubscriptionByIDReader is a Reader for the GetSubscriptionByID structure.
type GetSubscriptionByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSubscriptionByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSubscriptionByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetSubscriptionByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetSubscriptionByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSubscriptionByIDOK creates a GetSubscriptionByIDOK with default headers values
func NewGetSubscriptionByIDOK() *GetSubscriptionByIDOK {
	return &GetSubscriptionByIDOK{}
}

/*GetSubscriptionByIDOK handles this case with default header values.

successful operation
*/
type GetSubscriptionByIDOK struct {
	Payload *appmgr_model.Subscription
}

func (o *GetSubscriptionByIDOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}][%d] getSubscriptionByIdOK  %+v", 200, o.Payload)
}

func (o *GetSubscriptionByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(appmgr_model.Subscription)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSubscriptionByIDBadRequest creates a GetSubscriptionByIDBadRequest with default headers values
func NewGetSubscriptionByIDBadRequest() *GetSubscriptionByIDBadRequest {
	return &GetSubscriptionByIDBadRequest{}
}

/*GetSubscriptionByIDBadRequest handles this case with default header values.

Invalid ID supplied
*/
type GetSubscriptionByIDBadRequest struct {
}

func (o *GetSubscriptionByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}][%d] getSubscriptionByIdBadRequest ", 400)
}

func (o *GetSubscriptionByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSubscriptionByIDNotFound creates a GetSubscriptionByIDNotFound with default headers values
func NewGetSubscriptionByIDNotFound() *GetSubscriptionByIDNotFound {
	return &GetSubscriptionByIDNotFound{}
}

/*GetSubscriptionByIDNotFound handles this case with default header values.

Subscription not found
*/
type GetSubscriptionByIDNotFound struct {
}

func (o *GetSubscriptionByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}][%d] getSubscriptionByIdNotFound ", 404)
}

func (o *GetSubscriptionByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
