// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	appmgr_model "routing-manager/pkg/appmgr_model"
)

// ModifySubscriptionReader is a Reader for the ModifySubscription structure.
type ModifySubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifySubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifySubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewModifySubscriptionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifySubscriptionOK creates a ModifySubscriptionOK with default headers values
func NewModifySubscriptionOK() *ModifySubscriptionOK {
	return &ModifySubscriptionOK{}
}

/*ModifySubscriptionOK handles this case with default header values.

Subscription modification successful
*/
type ModifySubscriptionOK struct {
	Payload *appmgr_model.SubscriptionResponse
}

func (o *ModifySubscriptionOK) Error() string {
	return fmt.Sprintf("[PUT /subscriptions/{subscriptionId}][%d] modifySubscriptionOK  %+v", 200, o.Payload)
}

func (o *ModifySubscriptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(appmgr_model.SubscriptionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifySubscriptionBadRequest creates a ModifySubscriptionBadRequest with default headers values
func NewModifySubscriptionBadRequest() *ModifySubscriptionBadRequest {
	return &ModifySubscriptionBadRequest{}
}

/*ModifySubscriptionBadRequest handles this case with default header values.

Invalid input
*/
type ModifySubscriptionBadRequest struct {
}

func (o *ModifySubscriptionBadRequest) Error() string {
	return fmt.Sprintf("[PUT /subscriptions/{subscriptionId}][%d] modifySubscriptionBadRequest ", 400)
}

func (o *ModifySubscriptionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
