// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	appmgr_model "routing-manager/pkg/appmgr_model"
)

// NewModifySubscriptionParams creates a new ModifySubscriptionParams object
// with the default values initialized.
func NewModifySubscriptionParams() *ModifySubscriptionParams {
	var ()
	return &ModifySubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifySubscriptionParamsWithTimeout creates a new ModifySubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifySubscriptionParamsWithTimeout(timeout time.Duration) *ModifySubscriptionParams {
	var ()
	return &ModifySubscriptionParams{

		timeout: timeout,
	}
}

// NewModifySubscriptionParamsWithContext creates a new ModifySubscriptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewModifySubscriptionParamsWithContext(ctx context.Context) *ModifySubscriptionParams {
	var ()
	return &ModifySubscriptionParams{

		Context: ctx,
	}
}

// NewModifySubscriptionParamsWithHTTPClient creates a new ModifySubscriptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewModifySubscriptionParamsWithHTTPClient(client *http.Client) *ModifySubscriptionParams {
	var ()
	return &ModifySubscriptionParams{
		HTTPClient: client,
	}
}

/*ModifySubscriptionParams contains all the parameters to send to the API endpoint
for the modify subscription operation typically these are written to a http.Request
*/
type ModifySubscriptionParams struct {

	/*SubscriptionID
	  ID of subscription

	*/
	SubscriptionID int64
	/*SubscriptionRequest
	  Modified subscription

	*/
	SubscriptionRequest *appmgr_model.SubscriptionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the modify subscription params
func (o *ModifySubscriptionParams) WithTimeout(timeout time.Duration) *ModifySubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify subscription params
func (o *ModifySubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify subscription params
func (o *ModifySubscriptionParams) WithContext(ctx context.Context) *ModifySubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify subscription params
func (o *ModifySubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify subscription params
func (o *ModifySubscriptionParams) WithHTTPClient(client *http.Client) *ModifySubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify subscription params
func (o *ModifySubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubscriptionID adds the subscriptionID to the modify subscription params
func (o *ModifySubscriptionParams) WithSubscriptionID(subscriptionID int64) *ModifySubscriptionParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the modify subscription params
func (o *ModifySubscriptionParams) SetSubscriptionID(subscriptionID int64) {
	o.SubscriptionID = subscriptionID
}

// WithSubscriptionRequest adds the subscriptionRequest to the modify subscription params
func (o *ModifySubscriptionParams) WithSubscriptionRequest(subscriptionRequest *appmgr_model.SubscriptionRequest) *ModifySubscriptionParams {
	o.SetSubscriptionRequest(subscriptionRequest)
	return o
}

// SetSubscriptionRequest adds the subscriptionRequest to the modify subscription params
func (o *ModifySubscriptionParams) SetSubscriptionRequest(subscriptionRequest *appmgr_model.SubscriptionRequest) {
	o.SubscriptionRequest = subscriptionRequest
}

// WriteToRequest writes these params to a swagger request
func (o *ModifySubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", swag.FormatInt64(o.SubscriptionID)); err != nil {
		return err
	}

	if o.SubscriptionRequest != nil {
		if err := r.SetBodyParam(o.SubscriptionRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
